image: modm/modm-build:latest

variables:
  LANG: "en_US.UTF-8"
  SCONS_LIB_DIR: "/usr/local/lib/python3.6/dist-packages/scons-3.0.1"
  SCONSFLAGS: "-j3"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.roboterclub.rwth-aachen.de/rca/rca-ci-helper.git
  - rca-ci-helper/populate_rca_software.sh

gen-kicad-pcb-pdfs:
  image: ghcr.io/rleh/kicad5_and_pandoc:latest
  before_script:
    - which kicad
    - which kibot
    - kibot --version
  script:
    - export CONFIGFILE=$(readlink -f config.kibot.yaml)
    - cd kicad
    - for d in macro-motor/ micro-motor-v2/; do pushd $d; kibot -c ${CONFIGFILE}; popd; done
  artifacts:
    paths:
      - kicad/**/*pdf
    expire_in: 2 hours
# The latest artifacts of a branch or tag will be kept (with the default settings)!
# So no need to remove or increase the expiring time.

compile-src:
  script:
    - locale -a
    - scons --version
    - which arm-none-eabi-g++
    - arm-none-eabi-g++ --version
    - lbuild -h | head -n1
    - cd src/test_blink
    - lbuild build
    - scons
    - cd ../../src/test_can
    - lbuild build
    - scons
    - cd ../../src/test_gatedriver
    - lbuild build
    - scons
    - cd ../../src/test_pwm
    - lbuild build
    - scons
    - cd ../../src/test_dc_motor
    - lbuild build
    - scons
    - cd ../../src/test_bldc_motor
    - lbuild build
    - scons
