name: 'Setup modm'
description: 'Setup modm'
runs:
  using: "composite"
  steps:
    - name: Setup dependencies
      run: |
        apt update
        apt install scons python3-pyelftools python3-pip --yes
        pip install modm 
        wget -O- https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v13.2.1-1.1/xpack-arm-none-eabi-gcc-13.2.1-1.1-linux-x64.tar.gz | tar xz -C /opt/
        echo "/opt/xpack-arm-none-eabi-gcc-13.2.1-1.1/bin:${HOME}/.local/bin:" >> $GITHUB_PATH
    - name: Print versions
      run: |
        arm-none-eabi-gcc --version
        lbuild --version
        scons --version